apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  project: default
  source:
    repoURL: https://github.com/org/app-manifests
    path: base
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: app
